### ISSUE TITLE
displaying games created by other users

### ISSUE THREAD

**Issue by daniel-j-pease** [daniel-j-pease/soccer-finder#1]
Only users who create a game are able to see it after searching. See below:

<img width="510" alt="screen shot 2016-10-31 at 12 19 44 pm" src="https://cloud.githubusercontent.com/assets/20301442/19862087/5105cfa6-9f65-11e6-86aa-c54c6c33328a.png">
<img width="460" alt="screen shot 2016-10-31 at 12 21 34 pm" src="https://cloud.githubusercontent.com/assets/20301442/19862088/5105db0e-9f65-11e6-9f31-f3d79da8f752.png">
<img width="406" alt="screen shot 2016-10-31 at 12 21 50 pm" src="https://cloud.githubusercontent.com/assets/20301442/19862086/5103edb2-9f65-11e6-9d17-f9c69b25e86b.png">

I believe the following is to blame:
<img width="571" alt="screen shot 2016-10-31 at 12 29 16 pm" src="https://cloud.githubusercontent.com/assets/20301442/19862177/a9a4fd08-9f65-11e6-8871-22c406f4e114.png">

I tried:
-console logging 'games' every which where
-checking for the games in mongo shell to make sure they exist
-sticking this for loop all over the place
-editing the makeGame function in my games model so that the resulting object wasn't tied to a userid

Help!

**Comment by daniel-j-pease** [comment]
@gittheking
@trevorpreston
@rapala61
@irwintsay

**Comment by rapala61** [comment]
Please add me to your project as a collaborator

**Comment by daniel-j-pease** [comment]
added!

**Comment by daniel-j-pease** [comment]
nevermind! thanks anyway
